### ISSUE TITLE
iOS app list is messy

### ISSUE THREAD

**Issue by jdebp** [hueyy/awesome-mastodon#25]
Sometimes the link is to the Apple Store, sometimes it is to a WWW site, sometimes it is to a Fediverse account.  And there is inconsistencies between entries.  Some are marked "paid", others that are subscription-only are not marked "paid".

Without making the list too detailed, I think that it is possible to clean this up; supplying the three aforementioned pieces of information where available.

**Comment by jdebp** [comment]
Suggested text:

* Ice Cubes ([@icecubesapp@mastodon.cloud](https://mastodon.cloud/@icecubesapp), [Mac App Store](https://apps.apple.com/gb/app/ice-cubes-for-mastodon/id6444915884), [Testflight](https://testflight.apple.com/join/tqI3dK1u)) (open source, [GitHub](https://github.com/Dimillian/IceCubesApp)) - still under heavy development
* Ivory ([@ivory@tapbots.social](https://tapbots.social/@ivory)) (paid, closed source) - by the makers of TweetBot for Twitter, Early Access
* Mammoth ([@mammoth@moth.social](https://moth.social/@mammoth), [Testflight](https://testflight.apple.com/join/ejJ70WEq)) - by the maker of Aviary for Twitter, still in beta
* Mast: for Mastodon ([Mac App Store](https://apps.apple.com/us/app/mast-for-mastodon/id1437429129)) (paid)
* Mastoon ([Mac App Store](https://apps.apple.com/us/app/mastoon-for-mastodon/id1633757607))
* Mastoot ([@Mastoot@mastodon.online](https://mastodon.online/@Mastoot), [Mac App Store](https://apps.apple.com/us/app/mastoot/id1501485410)) - edit posts
* Mercury for Mastodon ([Mac App Store](https://apps.apple.com/us/app/mercury-for-mastodon/id1486749200))
* Metatext ([WWW](https://metabolist.org/), [Mac App Store](https://apps.apple.com/us/app/metatext/id1523996615)) (open source, [GitHub](https://github.com/metabolist/metatext)) - development has currently been suspended
* Mona ([@MonaApp@mastodon.social](https://mastodon.social/@MonaApp)) - still in testing phase
* Osakadon ([@osakadon_ios@mstdn.osaka](https://mstdn.osaka/@osakadon_ios), [Mac App Store](https://apps.apple.com/app/id1239260388)) - Japanese language only
* Oyakodon ([@isaotakeyasu@mstdn.jp](https://mstdn.jp/@isaotakeyasu), [Mac App Store](https://apps.apple.com/gb/app/oyakodon-for-mastodon/id1229174544))
* Tooot ([@tooot@xmflsct.com](https://xmflsct.com/@tooot), [WWW](https://tooot.app), [Mac App Store](https://apps.apple.com/gb/app/tooot/id1549772269)) (open source, [GitHub](https://github.com/tooot-app/app)) - started with a focus for Chinese community; now translated to other languages as well; edit posts
* Toot! ([@tootapp@mastodon.social](https://mastodon.social/@tootapp), [Mac App Store](https://apps.apple.com/us/app/toot/id1229021451)) (paid, closed source)
* Tootter ([Mac App Store](https://apps.apple.com/us/app/tootter-for-mastodon/id1629293955))
* Tootle for Mastodon ([@tootleapp@mastodon.cloud](https://mastodon.cloud/@tootleapp), [Mac App Store](https://apps.apple.com/us/app/tootle-for-mastodon/id1236013466)) - iPad, regular expression filters
* Tootoise ([Mac App Store](https://apps.apple.com/us/app/tootoise/id1465090190), [Testflight](https://testflight.apple.com/join/2LVAJQTP)) - still in testing phase
* Trunk ([@davbeck@mastodon.social](https://mastodon.social/@davbeck/109509705243442173)) - with a unique scrolling concept: Instead of scrolling vertically through your timeline, Trunk shows the full detail of each post, and you swipe right to left to go through the timeline. This may encourage better engagement and more focus on each individual post.
* Tusker ([@shadowfacts@social.shadowfacts.net](https://social.shadowfacts.net/@shadowfacts), [WWW](https://vaccor.space/tusker/), [Mac App Store](https://apps.apple.com/gb/app/tusker/id1498334597)) - for Pleroma as well; still a work in progress
* Woolly for Mastodon ([@mttvll@mastodon.social](https://mastodon.social/@mttvll/109546787074477406), [Testflight](https://testflight.apple.com/join/2LVAJQTP)) - still in the early stages of development

**Comment by jdebp** [comment]
A quick perusal of https://bilge.world/mastodon-ios-apps shows that this is still missing iMast, Amaroq, the [WWW](https://onmercury.app/) page for Mercury, Roma, Fedi, DUDU, Stella, B4X, StarPterano, and Ore2.

**Comment by kevjaro** [comment]
I would suggest a few changes:

1. making the Mastodon links more uniform would probably look a bit nicer, e.g. [Mastodon](https://example.org) instead of [@Mastodon@example.org](https://example.org) (You can usually just input the full link into the search bar on your Mastodon client of choice)
2. changing *Mac App Store* to *App Store* since they're iOS apps, not Mac
3. I personally think [Website](https://example.org) would look better and would be more understandable than [WWW](https://example.org)
4. A few of those are still missing descriptions. Can just take a shortened version of the description on the App Store.
5. Is the Mastoon link working for you? It isn't on my end.
6. The Mastodon link for Tooot is invalid
7. The Mastodon link for Trunk should be the profile link, not a post link
8. The Mastodon link for Tusker is invalid
9. The Mastodon link for Woolly should be the profile link, not a post link
10. Tootle Testflight actually links to Woolly

If you'd like to fix those and make a PR, that'd be great. Otherwise I can do that later if you want.

Thanks for the work!

**Comment by kevjaro** [comment]
Also there's a bit of an issue with the rest of the links on this page if we do it this way, since the App section would then be the only one in this format:
App Name (*Link1* *Link2*) (*Source link*) - Description

We could just change the order a bit:
1. The App name should be the App Store/ Play Store link. If that's not available, use the Testflight/ Play Store Early Access/ F-Droid link. If that's not available, the Code Repository. If there's only a website or profile link and no way of installing it, ignore the whole app since it won't be useful to most, or maybe put it in another section?
2. Mentioning that an app is open-source/ close-source isn't particularly helpful and just causes clutter. Better just put the [Link](https://example.org) there instead. If there's not link, it's closed-source.
3. As for the rest of the layout, I'd put it like this:

* [Mastodon App](https://example.org) ([Website](https://example.org) | [Mastodon](https://example.org) | [Testflight](https://example.org) | [GitHub](https://example.org) || *paid*) - a Mastodon client, *in Early Access*

**Comment by kevjaro** [comment]
Done. Hopefully acceptable :)

**Comment by hueyy** [comment]
Resolved by #27
